# The default config file. You may override configs with `key=value` arguments on the CLI
# according to https://hydra.cc/docs/advanced/override_grammar/basic/.

# This defines the order in which configs are loaded. The latter configs
# override the earlier ones.
defaults:
  - _self_ # refers to this config file
  - model: llama-3-8b # refers to model/llama-3-8b.yaml

dataset_name: wikitext
dataset_config_name: wikitext-2-raw-v1
global_batch_size: 8
logging_steps: 10
max_steps: 15
block_size: 8192
cache_dir: /tmp/
seed: 42
profile_step: -1

# This might be overwritten when using tp run to launch the run using XPK
profile_dir: profile
profile_duration: 100000
optimizer:
  learning_rate: 5.e-5
lr_scheduler:
  type: linear
  warmup_steps: 0
mesh:
  dcn: 1
  fsdp: 4
  tensor: 1
  expert: 1
